package com.drvidal.qrscanner.presentation.ui.theme
import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF335da8)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFd7e2ff)
val md_theme_light_onPrimaryContainer = Color(0xFF001a43)
val md_theme_light_secondary = Color(0xFF00677c)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFadecff)
val md_theme_light_onSecondaryContainer = Color(0xFF001f27)
val md_theme_light_tertiary = Color(0xFF046e17)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFF9af890)
val md_theme_light_onTertiaryContainer = Color(0xFF002201)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfbfdfd)
val md_theme_light_onBackground = Color(0xFF191c1d)
val md_theme_light_surface = Color(0xFFfbfdfd)
val md_theme_light_onSurface = Color(0xFF191c1d)
val md_theme_light_surfaceVariant = Color(0xFFe6e0ec)
val md_theme_light_onSurfaceVariant = Color(0xFF48454f)
val md_theme_light_outline = Color(0xFF79767f)
val md_theme_light_inverseOnSurface = Color(0xFFeff1f1)
val md_theme_light_inverseSurface = Color(0xFF2d3132)
val md_theme_light_inversePrimary = Color(0xFFacc6ff)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFacc6ff)
val md_theme_dark_onPrimary = Color(0xFF002d6d)
val md_theme_dark_primaryContainer = Color(0xFF12448f)
val md_theme_dark_onPrimaryContainer = Color(0xFFd7e2ff)
val md_theme_dark_secondary = Color(0xFF58d6f6)
val md_theme_dark_onSecondary = Color(0xFF003642)
val md_theme_dark_secondaryContainer = Color(0xFF004e5e)
val md_theme_dark_onSecondaryContainer = Color(0xFFadecff)
val md_theme_dark_tertiary = Color(0xFF7fdb77)
val md_theme_dark_onTertiary = Color(0xFF003a04)
val md_theme_dark_tertiaryContainer = Color(0xFF005308)
val md_theme_dark_onTertiaryContainer = Color(0xFF9af890)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF191c1d)
val md_theme_dark_onBackground = Color(0xFFe0e3e3)
val md_theme_dark_surface = Color(0xFF191c1d)
val md_theme_dark_onSurface = Color(0xFFe0e3e3)
val md_theme_dark_surfaceVariant = Color(0xFF48454f)
val md_theme_dark_onSurfaceVariant = Color(0xFFc9c4cf)
val md_theme_dark_outline = Color(0xFF938f99)
val md_theme_dark_inverseOnSurface = Color(0xFF191c1d)
val md_theme_dark_inverseSurface = Color(0xFFe0e3e3)
val md_theme_dark_inversePrimary = Color(0xFF335da8)
val md_theme_dark_shadow = Color(0xFF000000)

val seed = Color(0xFF6750A4)
val error = Color(0xFFB3261E)